<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-5BQ8UDAV" failures="1" tests="2" name="test1" time="0.048" errors="0" timestamp="2020-11-30T19:02:02 CST">
  <testcase classname="com.webtest.demo.Demo" name="test1" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.demo.Demo.test1(Demo.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="com.webtest.demo.Demo" name="test2" time="0.001"/>
</testsuite> <!-- test1 -->
